//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FichadaBinser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FichadaBinser.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cancelar el Inicio de Almuerzo?.
        /// </summary>
        public static string ConfirmCancelEndLunch {
            get {
                return ResourceManager.GetString("ConfirmCancelEndLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cancelar el Ingreso?.
        /// </summary>
        public static string ConfirmCancelEntry {
            get {
                return ResourceManager.GetString("ConfirmCancelEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cancelar el Egreso?.
        /// </summary>
        public static string ConfirmCancelExit {
            get {
                return ResourceManager.GetString("ConfirmCancelExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cancelar el Fin de Almuerzo?.
        /// </summary>
        public static string ConfirmCancelStartLunch {
            get {
                return ResourceManager.GetString("ConfirmCancelStartLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea guardar los cambios?.
        /// </summary>
        public static string ConfirmSaveChanges {
            get {
                return ResourceManager.GetString("ConfirmSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario Incorrecto.
        /// </summary>
        public static string IncorrectTime {
            get {
                return ResourceManager.GetString("IncorrectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete el horario de fin de almuerzo..
        /// </summary>
        public static string ValidationCompleteEndLunchTime {
            get {
                return ResourceManager.GetString("ValidationCompleteEndLunchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete el horario de ingreso..
        /// </summary>
        public static string ValidationCompleteEntryTime {
            get {
                return ResourceManager.GetString("ValidationCompleteEntryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete el horario de egreso..
        /// </summary>
        public static string ValidationCompleteExitTime {
            get {
                return ResourceManager.GetString("ValidationCompleteExitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El horario de ingreso no puede ser mayor al horario de egreso..
        /// </summary>
        public static string ValidationEntryTimeGreaterThanExitTime {
            get {
                return ResourceManager.GetString("ValidationEntryTimeGreaterThanExitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El horario de ingreso no puede ser mayor al horario de inicio de almuerzo..
        /// </summary>
        public static string ValidationEntryTimeGreaterThanStartLunchTime {
            get {
                return ResourceManager.GetString("ValidationEntryTimeGreaterThanStartLunchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario inválido..
        /// </summary>
        public static string ValidationInvalidTime {
            get {
                return ResourceManager.GetString("ValidationInvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El horario de inicio de almuerzo no puede ser mayor al horario de fin de almuerzo..
        /// </summary>
        public static string ValidationStartLunchTimeGreaterThanEndLunchTime {
            get {
                return ResourceManager.GetString("ValidationStartLunchTimeGreaterThanEndLunchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El horario de inicio de almuerzo no puede ser mayor al horario egreso..
        /// </summary>
        public static string ValidationStartLunchTimeGreaterThanExitTime {
            get {
                return ResourceManager.GetString("ValidationStartLunchTimeGreaterThanExitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
